### ISSUE TITLE
Port Binding Issue with Tomcat Container in Wallet PID Provider Docker Setup

### ISSUE THREAD

**Issue by hevelius** [italia/eudi-wallet-it-openid-credential-issuer#1]
I think there is an error in the readme or tomcat xml configuration.

https://github.com/italia/eudi-wallet-it-pid-provider/blob/2f456956a420113bc803034c032310566b204fb6/README.md?plain=1#L22-L24

To run the container a binding to port 8080:80 is suggested but Tomcat seems to work on port 8080 instead. The readme file could be updated to run `docker run -p 8080:8080 eudi-it-wallet-pid-provider` on the port 8080 or refactor src to run tomcat container on port 80

Tips: what do you think to add a .gitignore file to exclude target directory?

**Comment by sviluppo-ipzs** [comment]
The README file has been updated in version 1.1.1
